name: Build Docs

on: push

jobs:
  rulebook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/fb6c3a6831ca5c5a9d923fed1db3c2006a118681.tar.gz
    - name: Build rulebook
      run: |
        nix-build -A rulebook
    - uses: actions/upload-artifact@v1
      with:
        name: rulebook
        path: result
