name: Build Docs

on: push

jobs:
  rulebook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - name: Build rulebook
      run: |
        nix-build -A rulebook
    - uses: actions/upload-artifact@v1
      with:
        name: rulebook
        path: result
