name: Build Docs

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir docs
      - uses: docker://pandoc/latex:2.9
        with: # needs a README in your repo root!
          args: "--output=docs/RULES.pdf RULES.md"
      - uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs
