name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - name: Build cards
      run: |
        OUTS=$(nix-build default.nix -A rendered.cards.all --no-out-link)
        mkdir cards-tmp
        for O in $OUTS; do cp $O/singles/*.png cards-tmp/; done
    - uses: actions/upload-artifact@v1
      with:
        name: cards
        path: cards-tmp
    - name: Build decks
      run: |
        OUTS=$(nix-build default.nix -A rendered.decks.all --no-out-link)
        mkdir decks-tmp
        for O in $OUTS; do cp $O/sheets/*.png decks-tmp/; done
    - uses: actions/upload-artifact@v1
      with:
        name: decks
        path: decks-tmp
